### ISSUE TITLE
docker-compose-rt

### ISSUE THREAD

**Issue by rccclr** [cloos/docker-rt#4]
Hello

many thanks for your work.
I used the version 4.4 from docker and run perfect.
But with docker-compose has a problem.
If you have a configuration with docker-compose, its possible shared?

Regards

**Comment by cloos** [comment]
I don't use docker-compose.
But what problem do you have with this image and docker-compose?

**Comment by rccclr** [comment]
Thanks Christian
No problem with your image.
With docker-compose possible the error its for me.
The next month work in a integration rt with Oracle.
When its ok, shared with you.
Many thanks
