### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by JrMiaoRenFeng** [cloos/docker-rt#5]
Hello, netsandbox, I use your image to build RT, but I don't know how to operate the database, can you tell me how to operate the database? Looking forward for your reply, thank you.

**Comment by cloos** [comment]
What do you mean by "operate the database"?

**Comment by JrMiaoRenFeng** [comment]
Thank you for your reply, that is, I want to add, delete, change, and check the database “SQLite”, but I don't know where to write the sql statement. can you tell me?

**Comment by cloos** [comment]
It is not a good idea to mess with the RT database.
But if you know what you are doing, then run your sqlite command, but you have to run it inside of the container like:
`docker exec <container name> bash -c "<sqlite command>"`
